# LendingClub Bank Predictor The Default And Fully Paid Loans Fully Project

In [ ]:
import pandas as pd           
import numpy as np           
from sqlalchemy import create_engine
from sqlalchemy import text


print("Imported")

Imported

In [ ]:
# MySQL Connection
DB_USER     = 'root'
DB_PASSWORD = '123456'
DB_HOST     = 'localhost'
DB_PORT     = 3306
DB_NAME     = 'lendingclub'

MySQL = f'mysql+pymysql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}'
engine = create_engine(MySQL)
connection = engine.connect()


conn = engine.connect()
# Check if the connection is successful
conn.execute(text("SELECT 1"))
print("Connection to MySQL database was successful!")

Connection to MySQL database was successful!

In [ ]:
# Import datasets
df_accepted = pd.read_csv('D:/LendingCLub/Datasets/accepted_sample_loan.csv',dtype = str, low_memory=False)
df_rejected = pd.read_csv('D:/LendingCLub/Datasets/rejected_sample_loan.csv',dtype = str, low_memory=False)

print("Accepted Loans DataFrame:")
print(df_accepted.shape)
print("\nRejected Loans DataFrame:")
print(df_rejected.shape)

Accepted Loans DataFrame:
(2260701, 151)

Rejected Loans DataFrame:
(27648741, 9)

## Step 3: Data Understanding

In [9]:
df_accepted.shape

(2260701, 151)

In [11]:
df_rejected.shape

(27648741, 9)

In [12]:
print('First 5 rows of accepted loans:')
df_accepted.head()

First 5 rows of accepted loans:

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,68407277,NaN,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,68355089,NaN,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,68341763,NaN,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,66310712,NaN,35000.0,35000.0,35000.0,60 months,14.85,829.9,C,C5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,68476807,NaN,10400.0,10400.0,10400.0,60 months,22.45,289.91,F,F1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:

print('Accepted Loans Summary statistics:')
df_accepted.describe().round(2)

Accepted Loans Summary statistics:

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
count,2260701,0,2260668,2260668,2260668,2260668,2260668,2260668,2260668,2260668,...,10917,10917,2260668,2260668,34246,34246,34246,34246,34246,34246
unique,2260701,0,1572,1572,10057,2,673,93301,7,35,...,10893,9045,2,2,83,3,90,21941,2070,40
top,68407277,NaN,10000.0,10000.0,10000.0,36 months,11.99,301.15,B,C1,...,9599.86,0.02,Cash,N,Feb-2019,ACTIVE,Jan-2019,5000.0,45.0,18.0
freq,1,NaN,187236,187146,177561,1609754,53869,4420,663557,145903,...,2,25,2182546,2226422,2606,14704,1710,65,11919,6977

In [14]:
print('Rejected LoansSummary statistics:')
df_rejected.describe().round(2)

Rejected LoansSummary statistics:

,Amount Requested,Application Date,Loan Title,Risk_Score,Debt-To-Income Ratio,Zip Code,State,Employment Length,Policy Code
count,27648741,27648741,27647436,9151111,27648741,27648448,27648719,26697386,27647823
unique,3640,4238,73927,692,126145,1001,51,11,2
top,10000.0,2018-12-04,Debt consolidation,501.0,100%,112xx,CA,< 1 year,0.0
freq,3920004,42112,6418016,178456,1362556,267102,3242169,22994315,27559694

In [ ]:
# Missing values of Accepted loans 
missing = df_accepted.isnull().sum()
missing_pct = (missing / len(df_accepted) * 100).round(2)

missing_df = pd.DataFrame({
    'Missing Count': missing,
    'Missing %'    : missing_pct}).query('`Missing Count` > 0').sort_values('Missing(%)', ascending=False)

print('Columns with missing values:')
print(missing_df.to_string())

Columns with missing values:
                                            Missing Count  Missing %
member_id                                         2260701     100.00
orig_projected_additional_accrued_interest        2252050      99.62
hardship_dpd                                      2249784      99.52
hardship_status                                   2249784      99.52
deferral_term                                     2249784      99.52
hardship_amount                                   2249784      99.52
hardship_start_date                               2249784      99.52
hardship_end_date                                 2249784      99.52
payment_plan_start_date                           2249784      99.52
hardship_length                                   2249784      99.52
hardship_loan_status                              2249784      99.52
hardship_type                                     2249784      99.52
hardship_payoff_balance_amount                    2249784      99.52
hardship_last_payment_amount                      2249784      99.52
hardship_reason                                   2249784      99.52
debt_settlement_flag_date                         2226455      98.49
settlement_status                                 2226455      98.49
settlement_date                                   2226455      98.49
settlement_amount                                 2226455      98.49
settlement_percentage                             2226455      98.49
settlement_term                                   2226455      98.49
sec_app_mths_since_last_major_derog               2224759      98.41
sec_app_revol_util                                2154517      95.30
sec_app_earliest_cr_line                          2152680      95.22
sec_app_num_rev_accts                             2152680      95.22
sec_app_fico_range_high                           2152680      95.22
sec_app_inq_last_6mths                            2152680      95.22
sec_app_mort_acc                                  2152680      95.22
sec_app_open_acc                                  2152680      95.22
sec_app_open_act_il                               2152680      95.22
sec_app_fico_range_low                            2152680      95.22
revol_bal_joint                                   2152681      95.22
sec_app_chargeoff_within_12_mths                  2152680      95.22
sec_app_collections_12_mths_ex_med                2152680      95.22
verification_status_joint                         2144971      94.88
dti_joint                                         2139995      94.66
annual_inc_joint                                  2139991      94.66
desc                                              2134636      94.42
mths_since_last_record                            1901545      84.11
mths_since_recent_bc_dlq                          1741000      77.01
mths_since_last_major_derog                       1679926      74.31
mths_since_recent_revol_delinq                    1520342      67.25
next_pymnt_d                                      1345343      59.51
mths_since_last_delinq                            1158535      51.25
il_util                                           1068883      47.28
mths_since_rcnt_il                                 909957      40.25
all_util                                           866381      38.32
open_il_24m                                        866162      38.31
open_il_12m                                        866162      38.31
open_act_il                                        866162      38.31
open_acc_6m                                        866163      38.31
open_rv_24m                                        866162      38.31
max_bal_bc                                         866162      38.31
total_bal_il                                       866162      38.31
total_cu_tl                                        866163      38.31
inq_fi                                             866162      38.31
inq_last_12m                                       866163      38.31
open_rv_12m                                        866162      38.31
mths_since_recent_inq                              295468      13.07
emp_title                                          167002       7.39
num_tl_120dpd_2m                                   153690       6.80
emp_length                                         146940       6.50
mo_sin_old_il_acct                                 139104       6.15
bc_util                                             76104       3.37
percent_bc_gt_75                                    75412       3.34
bc_open_to_buy                                      74968       3.32
mths_since_recent_bc                                73445       3.25
pct_tl_nvr_dlq                                      70464       3.12
mo_sin_rcnt_tl                                      70309       3.11
num_op_rev_tl                                       70309       3.11
num_accts_ever_120_pd                               70309       3.11
num_actv_bc_tl                                      70309       3.11
num_actv_rev_tl                                     70309       3.11
num_bc_tl                                           70309       3.11
num_il_tl                                           70309       3.11
num_rev_accts                                       70310       3.11
num_rev_tl_bal_gt_0                                 70309       3.11
num_tl_30dpd                                        70309       3.11
num_tl_90g_dpd_24m                                  70309       3.11
num_tl_op_past_12m                                  70309       3.11
tot_hi_cred_lim                                     70309       3.11
total_il_high_credit_limit                          70309       3.11
mo_sin_old_rev_tl_op                                70310       3.11
mo_sin_rcnt_rev_tl_op                               70310       3.11
avg_cur_bal                                         70379       3.11
total_rev_hi_lim                                    70309       3.11
tot_cur_bal                                         70309       3.11
tot_coll_amt                                        70309       3.11
num_bc_sats                                         58623       2.59
num_sats                                            58623       2.59
total_bc_limit                                      50063       2.21
mort_acc                                            50063       2.21
acc_open_past_24mths                                50063       2.21
total_bal_ex_mort                                   50063       2.21
title                                               23359       1.03
last_pymnt_d                                         2460       0.11
dti                                                  1744       0.08
revol_util                                           1835       0.08
pub_rec_bankruptcies                                 1398       0.06
collections_12_mths_ex_med                            178       0.01
chargeoff_within_12_mths                              178       0.01
tax_liens                                             138       0.01
purpose                                                33       0.00
hardship_flag                                          33       0.00
earliest_cr_line                                       62       0.00
url                                                    33       0.00
pymnt_plan                                             33       0.00
loan_status                                            33       0.00
issue_d                                                33       0.00
verification_status                                    33       0.00
annual_inc                                             37       0.00
delinq_amnt                                            62       0.00
home_ownership                                         33       0.00
delinq_2yrs                                            62       0.00
sub_grade                                              33       0.00
fico_range_high                                        33       0.00
grade                                                  33       0.00
disbursement_method                                    33       0.00
debt_settlement_flag                                   33       0.00
installment                                            33       0.00
int_rate                                               33       0.00
term                                                   33       0.00
funded_amnt_inv                                        33       0.00
funded_amnt                                            33       0.00
fico_range_low                                         33       0.00
out_prncp                                              33       0.00
inq_last_6mths                                         63       0.00
open_acc                                               62       0.00
loan_amnt                                              33       0.00
acc_now_delinq                                         62       0.00
application_type                                       33       0.00
policy_code                                            33       0.00
last_fico_range_low                                    33       0.00
last_fico_range_high                                   33       0.00
last_credit_pull_d                                    105       0.00
last_pymnt_amnt                                        33       0.00
collection_recovery_fee                                33       0.00
recoveries                                             33       0.00
total_rec_late_fee                                     33       0.00
total_rec_int                                          33       0.00
total_rec_prncp                                        33       0.00
total_pymnt_inv                                        33       0.00
total_pymnt                                            33       0.00
out_prncp_inv                                          33       0.00
addr_state                                             33       0.00
initial_list_status                                    33       0.00
total_acc                                              62       0.00
revol_bal                                              33       0.00
pub_rec                                                62       0.00
zip_code                                               34       0.00

In [ ]:
# missing values of Rejected Loans 
missing = df_rejected.isnull().sum()
missing_pct = (missing / len(df_rejected) * 100).round(2)

rej_missing_df = pd.DataFrame({
    'Missing Count': missing,
    'Missing %'    : missing_pct
}).query('`Missing Count` > 0').sort_values('Missing %', ascending=False)

print('Columns with missing values:')
print(rej_missing_df.to_string())

Columns with missing values:
                   Missing Count  Missing %
Risk_Score              18497630      66.90
Employment Length         951355       3.44
Loan Title                  1305       0.00
Zip Code                     293       0.00
State                         22       0.00
Policy Code                  918       0.00

In [ ]:
# How many loans were paid off vs defaulted?
target_counts = df_accepted['loan_status'].value_counts()
target_pct    = df_accepted['loan_status'].value_counts(normalize=True).mul(100).round(1)

print('Loan Status Distribution:')
for status, count in target_counts.items():
    pct = target_pct[status]
    print(f'  {status:<15} : {count:>6} ({pct}%)')

Loan Status Distribution:
  Fully Paid      : 1,076,751 (47.6%)
  Current         : 878,317 (38.9%)
  Charged Off     : 268,559 (11.9%)
  Late (31-120 days) : 21,467 (0.9%)
  In Grace Period :  8,436 (0.4%)
  Late (16-30 days) :  4,349 (0.2%)
  Does not meet the credit policy. Status:Fully Paid :  1,988 (0.1%)
  Does not meet the credit policy. Status:Charged Off :    761 (0.0%)
  Default         :     40 (0.0%)

---
## Step 4: Data Cleaning

In [6]:
# Keep only relevant loan statuses
# We only care about COMPLETED loans: Fully Paid or Charged Off
print('All loan status values before filtering:')
print(df_accepted['loan_status'].value_counts())

All loan status values before filtering:
loan_status
Fully Paid                                             1076751
Current                                                 878317
Charged Off                                             268559
Late (31-120 days)                                       21467
In Grace Period                                           8436
Late (16-30 days)                                         4349
Does not meet the credit policy. Status:Fully Paid        1988
Does not meet the credit policy. Status:Charged Off        761
Default                                                     40
Name: count, dtype: int64

In [ ]:
# Keep only the two final statuses we care about
df_acc_clean = df_accepted[df_accepted['loan_status'].isin(['Fully Paid', 'Charged Off'])].copy()
print(f'Rows before filtering: {len(df_accepted)}')
print(f'Rows after  filtering: {len(df_acc_clean)}')
print(f'Rows removed         : {len(df_accepted) - len(df_acc_clean)}')

Rows before filtering: 2,260,701
Rows after  filtering: 1,345,310
Rows removed         : 915,391

In [ ]:
# Keep only the two final statuses we care about
df_rej_clean = df_rejected.copy()
print(f'Rejected loans: {len(df_rej_clean)}')

Rejected loans: 27,648,741

In [ ]:
# Create binary target variable
# 0 = Fully Paid (good loan)
# 1 = Charged Off (default ==> Target to predict)

df_acc_clean['target'] = (df_acc_clean['loan_status'] == 'Charged Off').astype(int)

print('Target variable created:')
print(df_acc_clean['target'].value_counts())
print('0 = Fully Paid (no default)')
print('1 = Charged Off (default)')

Target variable created:
target
0    1076751
1     268559
Name: count, dtype: int64
0 = Fully Paid (no default)
1 = Charged Off (default)

In [9]:
# extract term to number
if df_acc_clean['term'].dtype == object:
    df_acc_clean['term'] = df_acc_clean['term'].str.extract(r'(\d+)').astype(float)
    print('term column:')
    print(df_acc_clean['term'].value_counts())

term column:
term
36.0    1020743
60.0     324567
Name: count, dtype: int64

In [ ]:
# We convert it to a number years

emp_map = {
    '< 1 year': 0, '1 year': 1, '2 years': 2, '3 years': 3,
    '4 years': 4, '5 years': 5, '6 years': 6, '7 years': 7,
    '8 years': 8, '9 years': 9, '10+ years': 10
}

if df_acc_clean['emp_length'].dtype == object:
    df_acc_clean['emp_length'] = df_acc_clean['emp_length'].map(emp_map)

print('emp_length after conversion:')
print(df_acc_clean['emp_length'].describe().round(2))

emp_length after conversion:
count    1266799.00
mean           5.97
std            3.69
min            0.00
25%            2.00
50%            6.00
75%           10.00
max           10.00
Name: emp_length, dtype: float64

In [11]:
# Fix emp_length for Rejected Loans DataFrame

emp_map = {
    '< 1 year': 0, '1 year': 1, '2 years': 2, '3 years': 3,
    '4 years': 4, '5 years': 5, '6 years': 6, '7 years': 7,
    '8 years': 8, '9 years': 9, '10+ years': 10
}

if df_rej_clean['Employment Length'].dtype == object:
    df_rej_clean['Employment Length'] = df_rej_clean['Employment Length'].map(emp_map)

print('Employment Length after conversion:')
print(df_rej_clean['Employment Length'].describe().round(2))

NameError: name 'df_rej_clean' is not defined

In [ ]:
#remove all outliers from the accepted loans dataset using the IQR method and then save the cleaned dataset
def remove_outliers_iqr(df, column):
    # Convert column to numeric
    df[column] = pd.to_numeric(df[column], errors='coerce')
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return df[(df[column] >= lower_bound) & (df[column] <= upper_bound)]

# Convert numeric columns to numeric types before removing outliers
numeric_columns = ['loan_amnt', 'int_rate', 'installment', 'annual_inc', 'dti', 'fico_range_low', 'open_acc', 'pub_rec', 'revol_util']
for col in numeric_columns:
    if col in df_accepted.columns:
        df_accepted[col] = pd.to_numeric(df_accepted[col], errors='coerce')

# Remove outliers from the 'loan_amnt' column in the accepted loans dataset
df_no_outliers = remove_outliers_iqr(df_acc_clean.copy(), 'loan_amnt')
print(f'Accepted Loans after removing outliers: {df_no_outliers.shape[0]:,} rows')

Accepted Loans after removing outliers: 1,338,153 rows

In [ ]:
# remove outliers from the rejected loans dataset using the IQR method
df_rejected_no_outliers = remove_outliers_iqr(df_rej_clean.copy(), 'loan_amnt')
print(f'Rejected Loans after removing outliers: {df_rejected_no_outliers.shape[0]:} rows')

NameError: name 'df_rej_clean' is not defined

In [ ]:
# numeric and categorical columns
numeric_cols = df_acc_clean.select_dtypes(include="number").columns.tolist()
categorical_cols = df_acc_clean.select_dtypes(include="object").columns.tolist()

numeric_cols = [col for col in numeric_cols if col != "target"]

# Fill missing values for numeric columns with the median
for col in numeric_cols:
    missing_count = df_acc_clean[col].isnull().sum()
    if missing_count > 0:
        median_value = df_acc_clean[col].median()
        df_acc_clean[col].fillna(median_value, inplace=True)
        print(f"{col}: filled with median = {median_value:.2f} (missing: {missing_count})")
    else:
        print(f"{col}: no missing values")

# Fill missing values for categorical columns with the mode
for col in categorical_cols:
    # skip the loan_status column
    if col == "loan_status":
        continue

    missing_count = df_acc_clean[col].isnull().sum()
    if missing_count > 0:
        mode_values = df_acc_clean[col].mode()
        if not mode_values.empty:
            mode_value = mode_values.iloc[0]
            df_acc_clean[col].fillna(mode_value, inplace=True)
            print(f"{col}: filled with mode = {mode_value} (missing: {missing_count})")
    else:
        print(f"{col}: no missing values")

# check for remaining missing values
total_missing = df_acc_clean.isnull().sum().sum()
print("\nMissing Values Check")
print("-" * 30)
print(f"Total missing values remaining: {total_missing}")

term: no missing values
emp_length: filled with median = 6.00 (missing: 78511)
id: no missing values

C:\Users\dell\AppData\Local\Temp\ipykernel_2316\1790756053.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_acc_clean[col].fillna(median_value, inplace=True)

loan_amnt: no missing values
funded_amnt: no missing values
funded_amnt_inv: no missing values
int_rate: no missing values
installment: no missing values
grade: no missing values
sub_grade: no missing values

C:\Users\dell\AppData\Local\Temp\ipykernel_2316\1790756053.py:29: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_acc_clean[col].fillna(mode_value, inplace=True)

emp_title: filled with mode = Teacher (missing: 85785)
home_ownership: no missing values
annual_inc: no missing values
verification_status: no missing values
issue_d: no missing values
pymnt_plan: no missing values
url: no missing values
desc: filled with mode =   (missing: 1221780)
purpose: no missing values
title: filled with mode = Debt consolidation (missing: 16660)
zip_code: filled with mode = 945xx (missing: 1)
addr_state: no missing values
dti: filled with mode = 18.0 (missing: 374)
delinq_2yrs: no missing values
earliest_cr_line: no missing values
fico_range_low: no missing values
fico_range_high: no missing values
inq_last_6mths: filled with mode = 0.0 (missing: 1)
mths_since_last_delinq: filled with mode = 12.0 (missing: 678743)
mths_since_last_record: filled with mode = 71.0 (missing: 1116755)
open_acc: no missing values
pub_rec: no missing values
revol_bal: no missing values
revol_util: filled with mode = 0.0 (missing: 857)
total_acc: no missing values
initial_list_status: no missing values
out_prncp: no missing values
out_prncp_inv: no missing values
total_pymnt: no missing values
total_pymnt_inv: no missing values
total_rec_prncp: no missing values
total_rec_int: no missing values
total_rec_late_fee: no missing values
recoveries: no missing values
collection_recovery_fee: no missing values
last_pymnt_d: filled with mode = Aug-2018 (missing: 2313)
last_pymnt_amnt: no missing values
last_credit_pull_d: filled with mode = Mar-2019 (missing: 55)
last_fico_range_high: no missing values
last_fico_range_low: no missing values
collections_12_mths_ex_med: filled with mode = 0.0 (missing: 56)
mths_since_last_major_derog: filled with mode = 45.0 (missing: 991560)
policy_code: no missing values
application_type: no missing values
annual_inc_joint: filled with mode = 100000.0 (missing: 1319510)
dti_joint: filled with mode = 18.1 (missing: 1319513)
verification_status_joint: filled with mode = Not Verified (missing: 1319715)
acc_now_delinq: no missing values
tot_coll_amt: filled with mode = 0.0 (missing: 67527)
tot_cur_bal: filled with mode = 0.0 (missing: 67527)
open_acc_6m: filled with mode = 0.0 (missing: 807713)
open_act_il: filled with mode = 1.0 (missing: 807712)
open_il_12m: filled with mode = 0.0 (missing: 807712)
open_il_24m: filled with mode = 1.0 (missing: 807712)
mths_since_rcnt_il: filled with mode = 4.0 (missing: 821928)
total_bal_il: filled with mode = 0.0 (missing: 807712)
il_util: filled with mode = 83.0 (missing: 880294)
open_rv_12m: filled with mode = 0.0 (missing: 807712)
open_rv_24m: filled with mode = 1.0 (missing: 807712)
max_bal_bc: filled with mode = 0.0 (missing: 807712)
all_util: filled with mode = 63.0 (missing: 807765)
total_rev_hi_lim: filled with mode = 10000.0 (missing: 67527)
inq_fi: filled with mode = 0.0 (missing: 807712)
total_cu_tl: filled with mode = 0.0 (missing: 807713)
inq_last_12m: filled with mode = 0.0 (missing: 807713)
acc_open_past_24mths: filled with mode = 3.0 (missing: 47281)
avg_cur_bal: filled with mode = 0.0 (missing: 67549)
bc_open_to_buy: filled with mode = 0.0 (missing: 61143)
bc_util: filled with mode = 0.0 (missing: 61912)
chargeoff_within_12_mths: filled with mode = 0.0 (missing: 56)
delinq_amnt: no missing values
mo_sin_old_il_acct: filled with mode = 125.0 (missing: 105575)
mo_sin_old_rev_tl_op: filled with mode = 132.0 (missing: 67528)
mo_sin_rcnt_rev_tl_op: filled with mode = 2.0 (missing: 67528)
mo_sin_rcnt_tl: filled with mode = 2.0 (missing: 67527)
mort_acc: filled with mode = 0.0 (missing: 47281)
mths_since_recent_bc: filled with mode = 3.0 (missing: 60221)
mths_since_recent_bc_dlq: filled with mode = 26.0 (missing: 1026290)
mths_since_recent_inq: filled with mode = 1.0 (missing: 174071)
mths_since_recent_revol_delinq: filled with mode = 13.0 (missing: 895348)
num_accts_ever_120_pd: filled with mode = 0.0 (missing: 67527)
num_actv_bc_tl: filled with mode = 3.0 (missing: 67527)
num_actv_rev_tl: filled with mode = 4.0 (missing: 67527)
num_bc_sats: filled with mode = 3.0 (missing: 55841)
num_bc_tl: filled with mode = 5.0 (missing: 67527)
num_il_tl: filled with mode = 4.0 (missing: 67527)
num_op_rev_tl: filled with mode = 6.0 (missing: 67527)
num_rev_accts: filled with mode = 10.0 (missing: 67528)
num_rev_tl_bal_gt_0: filled with mode = 4.0 (missing: 67527)
num_sats: filled with mode = 9.0 (missing: 55841)
num_tl_120dpd_2m: filled with mode = 0.0 (missing: 117401)
num_tl_30dpd: filled with mode = 0.0 (missing: 67527)
num_tl_90g_dpd_24m: filled with mode = 0.0 (missing: 67527)
num_tl_op_past_12m: filled with mode = 1.0 (missing: 67527)
pct_tl_nvr_dlq: filled with mode = 100.0 (missing: 67681)
percent_bc_gt_75: filled with mode = 0.0 (missing: 61555)
pub_rec_bankruptcies: filled with mode = 0.0 (missing: 697)
tax_liens: filled with mode = 0.0 (missing: 39)
tot_hi_cred_lim: filled with mode = 12500.0 (missing: 67527)
total_bal_ex_mort: filled with mode = 0.0 (missing: 47281)
total_bc_limit: filled with mode = 0.0 (missing: 47281)
total_il_high_credit_limit: filled with mode = 0.0 (missing: 67527)
revol_bal_joint: filled with mode = 0.0 (missing: 1326681)
sec_app_fico_range_low: filled with mode = 660.0 (missing: 1326680)
sec_app_fico_range_high: filled with mode = 664.0 (missing: 1326680)
sec_app_earliest_cr_line: filled with mode = Aug-2006 (missing: 1326680)
sec_app_inq_last_6mths: filled with mode = 0.0 (missing: 1326680)
sec_app_mort_acc: filled with mode = 0.0 (missing: 1326680)
sec_app_open_acc: filled with mode = 8.0 (missing: 1326680)
sec_app_revol_util: filled with mode = 0.0 (missing: 1327008)
sec_app_open_act_il: filled with mode = 1.0 (missing: 1326680)
sec_app_num_rev_accts: filled with mode = 9.0 (missing: 1326680)
sec_app_chargeoff_within_12_mths: filled with mode = 0.0 (missing: 1326680)
sec_app_collections_12_mths_ex_med: filled with mode = 0.0 (missing: 1326680)
sec_app_mths_since_last_major_derog: filled with mode = 1.0 (missing: 1338665)
hardship_flag: no missing values
hardship_type: filled with mode = INTEREST ONLY-3 MONTHS DEFERRAL (missing: 1339556)
hardship_reason: filled with mode = NATURAL_DISASTER (missing: 1339556)
hardship_status: filled with mode = COMPLETED (missing: 1339556)
deferral_term: filled with mode = 3.0 (missing: 1339556)
hardship_amount: filled with mode = 53.05 (missing: 1339556)
hardship_start_date: filled with mode = Sep-2017 (missing: 1339556)
hardship_end_date: filled with mode = Dec-2017 (missing: 1339556)
payment_plan_start_date: filled with mode = Oct-2017 (missing: 1339556)
hardship_length: filled with mode = 3.0 (missing: 1339556)
hardship_dpd: filled with mode = 0.0 (missing: 1339556)
hardship_loan_status: filled with mode = Late (16-30 days) (missing: 1339556)
orig_projected_additional_accrued_interest: filled with mode = 186.9 (missing: 1341551)
hardship_payoff_balance_amount: filled with mode = 10747.75 (missing: 1339556)
hardship_last_payment_amount: filled with mode = 0.11 (missing: 1339556)
disbursement_method: no missing values
debt_settlement_flag: no missing values
debt_settlement_flag_date: filled with mode = Jan-2019 (missing: 1312034)
settlement_status: filled with mode = COMPLETE (missing: 1312034)
settlement_date: filled with mode = Jan-2019 (missing: 1312034)
settlement_amount: filled with mode = 5000.0 (missing: 1312034)
settlement_percentage: filled with mode = 45.0 (missing: 1312034)
settlement_term: filled with mode = 18.0 (missing: 1312034)

Missing Values Check
------------------------------
Total missing values remaining: 2690620

In [ ]:
# Fill missing values for Rejected Loans
numeric_rej_cols     = df_rej_clean.select_dtypes(include='number').columns.tolist()
categorical_rej_cols = df_rej_clean.select_dtypes(include='object').columns.tolist()

# Fill numeric with median
for col in numeric_rej_cols:
    if df_rej_clean[col].isnull().sum() > 0:
        median_val = df_rej_clean[col].median()
        df_rej_clean[col] = df_rej_clean[col].fillna(median_val)
        print(f'  Filled {col} with median = {median_val:.2f}')

  Filled Risk_Score with median = 637.00
  Filled Employment Length with median = 0.00
  Filled Policy Code with median = 0.00

In [ ]:
# Fill categorical rejected data with mode 
for col in categorical_rej_cols:
    if df_rej_clean[col].isnull().sum() > 0:
        mode_series = df_rej_clean[col].mode()
        if not mode_series.empty:
            mode_value = mode_series.iloc[0]
            df_rej_clean[col] = df_rej_clean[col].fillna(mode_value)
            print(f"{col} Filled with mode: {mode_value}")
        else:
            print(f"{col} Skipped (all values are missing)")
            
# Verify: no missing values remain
total_rej_missing = df_rej_clean.isnull().sum().sum()
print(f'\nTotal missing values remaining With rejects: {total_rej_missing}')

Loan Title Filled with mode: Debt consolidation
Zip Code Filled with mode: 112xx
State Filled with mode: CA

Total missing values remaining With rejects: 0

In [ ]:
# Verify: no missing values remain
total_rej_missing = df_rej_clean.isnull().sum().sum()
print(f'\nTotal missing values remaining: {total_missing}')

Total missing values remaining: 2690620

In [ ]:
# Remove duplicate rows from Accepted Loans
before = len(df_acc_clean)
df_acc_clean = df_acc_clean.drop_duplicates()
after  = len(df_acc_clean)
print(f'Duplicates removed: {before - after}')
print(f'Final cleaned dataset: {df_acc_clean.shape[0]:,} rows × {df_acc_clean.shape[1]} columns')

Duplicates removed: 0
Final cleaned dataset: 1,345,310 rows × 152 columns

In [ ]:
# Remove duplicate rows from Accepted Loans
before = df_acc_clean.shape[0]
df_acc_clean = df_acc_clean.drop_duplicates(keep='first', inplace=False)
after = df_acc_clean.shape[0]

# results
duplicates_removed = before - after
print(f"Duplicates removed: {duplicates_removed}")
print(f"Final cleaned dataset: {df_acc_clean.shape[0]:} rows × {df_acc_clean.shape[1]} columns")

Duplicates removed: 0
Final cleaned dataset: 1,345,310 rows × 152 columns

In [16]:
# Required Columns
ACCEPTED_COLS = [
    "loan_amnt",
    "term",
    "int_rate",
    "installment",
    "grade",
    "emp_length",
    "home_ownership",
    "annual_inc",
    "purpose",
    "dti",
    "fico_range_low",
    "open_acc",
    "pub_rec",
    "revol_util",
    "loan_status",
    "issue_d",
    "target"
]

# Keep only columns that exist in df_acc_clean
acc_cols = [
    col for col in ACCEPTED_COLS
    if col in df_acc_clean.columns
]

# Keep only the selected columns
df_acc_clean = df_acc_clean[acc_cols]

print("Final cleaned dataset:")
print(f"Rows    : {df_acc_clean.shape[0]:,}")
print(f"Columns : {df_acc_clean.shape[1]}")

print("\nColumns:")
print(df_acc_clean.columns.tolist())

Final cleaned dataset:
Rows    : 1,345,310
Columns : 17

Columns:
['loan_amnt', 'term', 'int_rate', 'installment', 'grade', 'emp_length', 'home_ownership', 'annual_inc', 'purpose', 'dti', 'fico_range_low', 'open_acc', 'pub_rec', 'revol_util', 'loan_status', 'issue_d', 'target']

In [17]:
df_acc_clean.head()

,loan_amnt,term,int_rate,installment,grade,emp_length,home_ownership,annual_inc,purpose,dti,fico_range_low,open_acc,pub_rec,revol_util,loan_status,issue_d,target
0,3600.0,36.0,13.99,123.03,C,10.0,MORTGAGE,55000.0,debt_consolidation,5.91,675.0,7.0,0.0,29.7,Fully Paid,Dec-2015,0
1,24700.0,36.0,11.99,820.28,C,10.0,MORTGAGE,65000.0,small_business,16.06,715.0,22.0,0.0,19.2,Fully Paid,Dec-2015,0
2,20000.0,60.0,10.78,432.66,B,10.0,MORTGAGE,63000.0,home_improvement,10.78,695.0,6.0,0.0,56.2,Fully Paid,Dec-2015,0
4,10400.0,60.0,22.45,289.91,F,3.0,MORTGAGE,104433.0,major_purchase,25.37,695.0,12.0,0.0,64.5,Fully Paid,Dec-2015,0
5,11950.0,36.0,13.44,405.18,C,4.0,RENT,34000.0,debt_consolidation,10.2,690.0,5.0,0.0,68.4,Fully Paid,Dec-2015,0

In [ ]:
REJECTED_COLS_MAP = {
    'Amount Requested': 'loan_amnt',
    'Risk_Score': 'fico_range_low',
    'Debt-To-Income Ratio': 'dti',
    'Employment Length': 'emp_length'
}

df_rej_clean.rename(columns=REJECTED_COLS_MAP, inplace=True)
# Select only the columns that exist after renaming
rej_cols = [col for col in REJECTED_COLS_MAP.values() if col in df_rej_clean.columns]
df_rej_clean = df_rej_clean[rej_cols]

In [ ]:
df_rej_clean.head()

   loan_amnt  fico_range_low     dti  emp_length
0     1000.0           693.0     10%         4.0
1     1000.0           703.0     10%         0.0
2    11000.0           715.0     10%         1.0
3     6000.0           698.0  38.64%         0.0
4     1500.0           509.0   9.43%         0.0

In [ ]:
df_acc_clean.drop(columns=['Unnamed: 0'], inplace=True)
df_rej_clean.drop(columns=['Unnamed: 0'], inplace=True)

In [ ]:
# Save cleaned datasets to CSV files
df_acc_clean.to_csv('Datasets/accepted_sample_loans_clean.csv')
df_rej_clean.to_csv('Datasets/rejected_sample_loans_clean.csv')